HTTPArchive/legacy.httparchive.org

- bulktest/cleanup-requests.php
Fixed the table name for the mobile crawls and eliminated the row counting pass when actually deleting (cuts time in half)
> Fixed the request cleanup script

- about.php
Use the normal discussion contact path for donation inquiries. The email was getting nothing but spam.
> Removed archive.org donation email

- custom_metrics/almanac.js
https://www.webpagetest.org/custom_metrics.php?test=190628_4K_a646aef9fe95cc2fa5b2159d79662cea&run=1&cached=0
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/33
Counts the links or buttons only containing an icon.
> Add custom metric for 12.11

- custom_metrics/almanac.js
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/33
Addresses metrics 08.39 (SRI) and 14.2-4 (AMP plugin)
https://www.webpagetest.org/custom_metrics.php?test=190628_4V_06eaa519ab5251a4a8c2073cd72c2dc8&run=1&cached=0
https://www.webpagetest.org/custom_metrics.php?test=190628_P1_51f3807c082e4f5a7b5c7092ec22576f&run=1&cached=0
https://www.webpagetest.org/custom_metrics.php?test=190628_B5_4c6fca755c6ce2756756b1d04d6d38b7&run=1&cached=0
https://www.webpagetest.org/custom_metrics.php?test=190629_X7_2fe55c5f5415b83101648c2d86200055&run=1&cached=0
> Almanac custom metrics

- custom_metrics/almanac.js
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/33
https://www.webpagetest.org/custom_metrics.php?test=190630_RH_feb05f7887f923ad6d9e5f9bce25426b&run=1&cached=0
Wow, I was surprised that this actually caught the NYT website doing the desired behavior. `earlyHash` is 2 in this test.
Default view, anchors hidden until focused:
-----
Tabbing to the first anchor on the page make this become visible:
------
Second anchor:
> earlyHash custom metric

- custom_metrics/almanac.js
As @rviscomi commented for the [2020 media chapter](https://github.com/HTTPArchive/almanac.httparchive.org/issues/900#issuecomment-660275165), some sql queries are expensive because they search in response bodies using regexp contains
[picture img sql](https://github.com/HTTPArchive/almanac.httparchive.org/blob/2189e7b3d80b94a09c9a1c59926ea63b3fe17c34/sql/2019/04_Media/04_08.sql)
I have tried to add a custom metric in almanac.js. I do not know if the notation used by me is according to your standards (If the value requires more than one line of code,...). Please advise.
>  added custom metric for media chapter - picture tag containing img

- custom_metrics/security.js
This adds the following metrics:
* `allow` and `sandbox` attribute for `<iframe>` elements
* Elements with an `integrity` attribute
Upon merge, the '08.39' metric in almanac.js can be removed (superseded by the `sri-integrity` metric)
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/906
> Add custom metrics for Security chapter

- custom_metrics/ecommerce.js
Custom metric to check presence of AndroidAppLinks and iOSUniversalLinks by fetching meta resources. More details @ https://github.com/HTTPArchive/legacy.httparchive.org/pull/172#issuecomment-663994308
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/914
> Added custom metrics for eCommerce chapter

- custom_metrics/almanac.js
- custom_metrics/media.js
@rviscomi, here is another custom metric for the [2020 media chapter](https://github.com/HTTPArchive/almanac.httparchive.org/issues/900#issuecomment-660275165). 
[source/img with sizes attribute expensive sql with regexp](https://github.com/HTTPArchive/almanac.httparchive.org/blob/2189e7b3d80b94a09c9a1c59926ea63b3fe17c34/sql/2019/04_Media/04_06b.sql)
I combined both conditions in the same metric, just as in the original sql. They could also be split metrics. Also we could add an empty attribute condition - img[sizes]:not([sizes=""]). Please advise.
As for the tests:
[img sizes](https://www.webpagetest.org/custom_metrics.php?test=200720_ZN_74bb4163bcdd2aa25c0e58aeca955708&run=1&cached=0)
[source sizes](https://www.webpagetest.org/custom_metrics.php?test=200720_YZ_5f276fed83e36382e40654e2d71 …
> Custom metrics for Media

- custom_metrics/almanac.js
I've looked through all of the metrics from 2019 and created new functions to minimize the use of regex this year.
Here are the summaries:
| Metric | Function to use |
| ------ | --------------- |
| 04_04.sql | inline_svg_stats |
| 04_06.sql | images.(total_*) |
| 04_06b.sql | images.sizes_values |
| 04_08.sql | image_stats.total_pictures_with_img |
| 04_09a.sql | meta-nodes should already take care what is portable here |
| 04_09b.sql | meta-nodes should already take care what is portable here |
| 04_09c.sql | meta-nodes should already take care what is portable here |
| 04_09d.sql | meta-nodes and images.sizes_values |
| 04_19.sql | videos |
| 04_26.sql | images.images_using_loading_prop |
| 08_32.sql | Using headers |
| 08_33.sql | Using headers |
| 08_35-37.sql | Using headers |
| …
> New metrics and bug fixes

- custom_metrics/README.md
Clarify that the "Custom Metrics" link appears after you've clicked on "Details". It drove me crazy why I wasn't seeing any "Custom Metrics" link!
> Update Custom Metrics README

- custom_metrics/privacy.js
Returns `1` if IAB TCF is integrated on the page.
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/913
> Privacy custom metrics: IAB Transparency and Consent Framework

- custom_metrics/css-variables.js
Details here: https://github.com/leaverou/css-almanac/issues/1#issuecomment-664842386
Please note that this is written assuming a recent version of Chrome. If WPT runs an older one, please let me know so I can make changes.
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/898
> Add CSS variables custom metrics

- custom_metrics/almanac.js
- custom_metrics/markup.js
- custom_metrics/wpt_bodies.js
#188 
I checked all the custom metrics for potential issues with them using css selectors that needed to be set to case insensitive. This pull adds i to them to make them case insensitive.
I also found potential issue with third-parties.js but it's code is auto generated. It uses selectors to detect the generator meta tag, but I think will only capture that if generator is lowercase.
I did some basic testing to check a a few cases from each file to see that it was now being case insensitive, and that the scripts ran without errors.
> Added i to make selectors case insensitive

- custom_metrics/ecommerce.js
- custom_metrics/robots_txt.js
- custom_metrics/sass.js
fixes #192 
I tested each with a success scenario with the 5000ms timeout and a fail scenario caused by setting the timeout to 10ms.
ecommerce and robots_txt return this on timeout:
`{"message":"The user aborted a request.","error":{}}`
sass was a bit more complex. I don't know how to do a real world test for this. 
It uses async calls. One fetch was already in a try/catch which I tested by faking the scenario that causes the fetches. It would behave in the same way any error would have been handed before, eats it.
I added a try/catch to the  second fetch so that it behaves in the same way as the response not being ok.
> added fetchWithTimeout and error checking for when it does time out

- custom_metrics/security.js
`<link>` elements can have SRI, but use a `href` attribute to point to the resource
> include href attribute for SRI custom metric

- custom_metrics/css.js
react-jss and material-ui all use jss core, it is confusing if this metric is tied to react-jss library by naming
> Detection using data-jss essentially detects JSS core, 

- custom_metrics/event-names.js
- custom_metrics/initiators.js
- custom_metrics/pwa.js
This is a custom metric that we can use as a workaround for the HTTP Archive response bodies being unavailable. It may also be useful for the [PWA chapter](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2153) of the 2021 Web Almanac.
The process to get this data in and out of BigQuery is:
- merge this PR
- sync the WPT test server with this repo
- wait for the crawl to be completed
- query the `pages` dataset for the `_pwa` field in the HAR payload
Known issue: a page like https://developers.google.com/web/tools/chrome-user-experience-report/ installs a SW but its JS is so minified that there's no way to reliably parse the registration with a regex. I'd love to hear if there are better ways to detect which JS resource is a SW. (maybe we can borrow a technique from …
> PWA custom metric

- custom_metrics/Images.js
Track adoption of `decoding=async` attributes on images. This will be especially interesting to analyze in conjunction with the `inViewport` property, which I renamed to camelCase for consistency with other properties.
cc @kevinfarrugia
> Measure decoding attribute of images

- custom_metrics/Images.js
- custom_metrics/metric-summary.md
Updated the Images custom metric `inViewport` property to check if the image is within the viewport, compared to simply checking the `top` position.
Will be used in 2021 Resource Hints chapter.
Reference discussion: https://github.com/HTTPArchive/legacy.httparchive.org/pull/202#discussion_r647905245
I opted against using the `IntersectionObserver` because its `async` nature would add unnecessary complexity to the custom metric. Ultimately we want to return `true` if the image is in the visible viewport and do not need to monitor for changes resulting from scroll events.
**Sample WPT**
https://webpagetest.org/custom_metrics.php?test=210614_AiDcH0_5d6b574017a022b085beade79bf0deef&run=1&cached=0
```
[
{
"url": "https://placekitten.com/101/101",
"width": 101,
"height": 101,
"naturalWidth": …
```
> Improved lazy in viewport

- custom_metrics/pwa.js
Hi folks,
As discussed in #203 I decided to create a PR for this script (even when is not optimal), since, after analyzing some tests with @tunetheweb, having it merged for Monday's crawl could help us get an idea of the number of false negatives in `serviceWorkerInitiatedURLs`.
We have added three new fields to the response: `importScriptsInfo`, `swEventListenersInfo`, `wPropertiesInfo`, which use [Rick's script for Workbox detection](https://github.com/HTTPArchive/legacy.httparchive.org/blob/a6b419f65194abb81840be6e52cfbaedfb945b40/custom_metrics/pwa.js#L72) and combines it with the regular expressions used last year to detect SW events and properties ([sw_events.sql](https://github.com/HTTPArchive/almanac.httparchive.org/blob/a883df882114af3b641791f787c3359bede5d803/sql/2020/pwa/sw_even …
> New script to detect importScripts(), service worker events and service worker properties

- custom_metrics/a11y.js
- custom_metrics/almanac.js
- custom_metrics/metric-summary.md
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/2147
This PR adds five new metrics:
1. `form_control_a11y_tree`: A slimmed down version of the browser accessibility tree for form controls (select, input, textarea, buttons)
2. `fieldset_radio_checkbox`: Documents how many radios and checkboxes there are. Then checks how many of those inputs are correctly placed in a fieldset with a legend
3. `required_form_controls`: Scans for all the required form controls on the page. Looks for `required`, `aria-required`, or an asterisk at the start or end of the visible label
4. Track `<audio>` elements and their `<track>`s
5. Addition of a `total_with_track` metric to the `videos` section in almanac.js
This code has been tested on custom built pages …
> New A11Y metrics

- custom_metrics/almanac.js
- custom_metrics/metric-summary.md
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/2151
This PR adds one new metric: `link_protocols_used`.
It's purpose is to list all the different types of protocols used in links on the page (sms, tel, https, ...)
It has been tested on a [custom page](https://output.jsbin.com/vafomucutu/1) and amazon which has a slew of links. Everything works as expected.
[Amazon.com](https://www.webpagetest.org/custom_metrics.php?test=210627_AiDcA0_21f55b07202f0919c68f5da4a8afcfff&run=1&cached=0)
[Custom page](https://www.webpagetest.org/custom_metrics.php?test=210627_BiDcNH_445e26032bcf071fe5eff777839660b5&run=1&cached=0)
> New mobile web metric

- custom_metrics/pwa.js
This PR contains the following changes to pwa.js:
- Added  a new field `serviceWorkerInfo` that uses a new regular expression to detect service worker registrations, that  matches the cases that the original one was ignoring: for example relative paths and variables used as the service worker URL. [Here is](https://webpagetest.org/result/210802_BiDcAB_61a77c283d1cdc85b764aa97658e7a2d/?f=json) an example test for mobile.twtiter.com, which was originally ignored and now it's found under `serviceWorkerInfo`.
- Added the new variable `serviceWorkerInfo` to the conditions for the `serviceWorkerHeuristic`. Ideally, the number of detected service workers should approximate more closely to `serviceWorkerHeuristic`.
- Added the `fetch` event listener to `swEventListenersInfo`. We initially removed …
> New metric to detect service workers in pwa.js

- custom_metrics/css.js
Thanks again @tomayac for working on this script.
I started to analyze how sites have implemented a dark theme and decided to use the custom metric to see if worked. The sites I'm currently analyzing are: https://mobile.twitter.com, https://web.whatsapp.com, https://www.github.com, https://www.youtube.com and https://pwa.zdf.com.
Based on what I could see there, I'm suggesting the following changes:
- Allowing for zero (instead of one) or more spaces between `@media` and the parenthesis.
- Including a regex for `window.matchMedia()` as some sites seem to be checking `prefers-color-scheme` via JS.
- Checking all the response bodies, instead of just the stylesheets, as developers tend to add the dark CSS themes directly in the HTML or JS.
This last one is controversial, and I guess you …
> Suggestions for 'prefersColorScheme' custom metric

- custom_metrics/markup.js
Updated the `markup` custom metric to include `form` property containing the number of `form` elements in the page, `target` and `method` attributes and elements within each form.
Sample WPT
https://webpagetest.org/custom_metrics.php?test=211011_AiDc0S_19c860e38dfd192c218c189e3df59af2&run=1&cached=0
```
...
{
"form": {
"target": { "_blank": 2 },
"method": { "post": 1 },
"elements": [
{
"tagNames": { "fieldset": 1, "legend": 1, "input": 3 },
"types": { "text": 2, "submit": 1 },
"total": 5
},
{
"tagNames": { "input": 2, "button": 1 },
"types": { "submit": 1 },
"total": 3
}
],
"total": 2
}
}
...
```
> Added form markup custom metric

- custom_metrics/robots_txt.js
Discussed in comment here: https://github.com/HTTPArchive/almanac.httparchive.org/pull/2351#issuecomment-932691221.  The linter is going to complain and I will fix.  I stink at JS.
> Major rewrite to update robots_txt for new metrics.
