HTTPArchive/legacy.httparchive.org

- custom_metrics/third-parties.js
Proof of concept of #77 
First library is jQuery, can add more incrementally.
Inspired by http://www.ccs.neu.edu/home/arshad/publications/ndss2017jslibs.pdf
/cc toby@ccs.neu.edu
> custom metric for 3rd party libs

- docs/README.md
- docs/bigquery.md
Progress on https://github.com/HTTPArchive/httparchive/issues/79
> BigQuery docs

- docs/js-library-detection.md
Refers to issue #77 (@rviscomi)
> Add document explaining the limitations of the JS library detection methodology

- custom_metrics/third-parties.js
See https://github.com/HTTPArchive/httparchive/pull/78#discussion_r108254522
Example WPT: https://www.webpagetest.org/result/170328_CA_1G4M/1/details/#waterfall_view_step1
Example source code: http://codepen.io/anon/pen/jBemrB
Progress on https://github.com/HTTPArchive/httparchive/issues/77
> always append a version, even if null

- LICENSE.md
Also fill in the year/owner placeholders.
> mv COPYING LICENSE.md

- docs/README.md
- docs/changelog.json
Using changes logged at http://httparchive.org/about.php#testchanges
Closes #101
> changelog with docs

- bulktest/cleanup-requests.php
> remove dropped tables

- bulktest/batch_lib.inc
> ensure firstHtml is type html

- about.php
- downloads.php
Replace with discuss.httparchive.org
> Update links/refs to bigqueri.es

- custom_metrics/anchor_text.js
> custom metric: anchor text

- custom_metrics/anchor_text.js
Was only included in one crawl (9/1).
> Remove anchor text custom metric

- docs/README.md
- docs/changelog.json
https://github.com/HTTPArchive/beta.httparchive.org/pull/18
> Add a `more` prop to changelog entries

- bulktest/batch_lib.inc
Not sure how to test this. Looks like my editor has stripped trailing whitespace as well.
> Extend list of mimetypes and extensions for videos

- custom_metrics/almanac.js
This adds my 'Query Written' items for the Almanac.
cc @rviscomi
> Almanac custom metrics

- custom_metrics/almanac.js
https://www.webpagetest.org/custom_metrics.php?test=190628_9M_bd55e297a131fd6d5fe2a3d90bb25e04&run=1&cached=0
> Add priority hints metric

- custom_metrics/css.js
Custom metrics to find if the site is using styled-components or radium CSS-in-JS libraries.
@rviscomi Do I need to include css.js anywhere?
@LeaVerou I'll start ball rolling and let's see if we can get anywhere before deadline.
> Add CSS-in-JS libraries detection custom metrics

- custom_metrics/sass.js
Details here: https://github.com/leaverou/css-almanac/issues/39#issuecomment-665714420
> Add Sass custom metrics

- custom_metrics/css-variables.js
This PR does two things:
1. The custom properties added are removed at the end. This means that the code is now idempotent; it can run multiple times on the same website with the same results. It also means that if any other metrics traverse `document.styleSheets` they will not be affected if this runs first.
2. Duplicate siblings in the same `obj.children` array are collapsed into one object, with a `times` property indicating how many they were. Non-contiguous siblings are also collapsed, so this is a bit lossy, but it does not affect any of the things we may want to study in this data structure. This change reduced the size of the tree generated on my own website by 40%, though the savings were less impressive on other websites (basically the more generic the selectors that use custom …
> [css-variables] Cleanup added custom properties, collapse duplicate siblings

- bulktest/importurls.php
Progress on https://github.com/HTTPArchive/httparchive.org/issues/240
> Handle CrUX ranks

- custom_metrics/metric-summary.md
To help analysts get a quick overview of all the metrics we are tracking we will start providing summaries of each metric contained in each custom metrics file
> Creation of metric summary file

- custom_metrics/fugu-apis.js
Tries to detect Project Fugu APIs based on regular expressions that match in the source code of JavaScript and Web App Manifest for the **Web Almanac** chapter on **Capabilities**.
- [Test run](https://webpagetest.org/custom_metrics.php?test=210614_AiDc16_2093bbfad84e971de3b08f4257fe78e2&run=1&cached=0) for [fugu-greetings.glitch.me](https://fugu-greetings.glitch.me/): 
```json
{
"https:\/\/fugu-greetings.glitch.me\/js\/clipboard.mjs": ["Async Clipboard (Images)"],
"https:\/\/fugu-greetings.glitch.me\/js\/badge.mjs": ["Badging"],
"https:\/\/fugu-greetings.glitch.me\/js\/wake_lock.mjs": ["Screen Wake Lock"],
"https:\/\/fugu-greetings.glitch.me\/manifest.webmanifest": ["Web Share Target", "Web Share Target (Files)"]
}
```
- [Test run](https://webpagetest.org/custom_metrics.php?test=210614_Bi …
> Add custom metrics for Project Fugu APIs

- custom_metrics/fugu-apis.js
(Sorry, forgot about this one.)
> [Custom Fugu metrics] Add Gamepad detection

- custom_metrics/fugu-apis.js
- Differentiate WebOTP and Credential Management. 
- Add more data to the object.
> Some refinements to the Fugu custom metrics

- custom_metrics/almanac.js
- custom_metrics/performance.js
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/2148
https://www.webpagetest.org/jsonResult.php?test=210630_AiDcW5_45f47b83f50f2cfd80d460827d845164&pretty=1 is the test result JSON with `lcp_stats` as the custom metric.
> Performance 2021 custom metrics

- custom_metrics/pwa.js
As discussed in https://github.com/HTTPArchive/almanac.httparchive.org/issues/2153#issuecomment-874570418
> Fix service worker base origin

- custom_metrics/performance.js
Augment the `performance` custom metric with a function that detects the presence of web-vitals.js based on patterns in its response body
cc @philipwalton
> Detect web-vitals.js

- custom_metrics/fugu-apis.js
- package-lock.json
- package.json
Updates to the latest Fugu data.
> Bump dependencies for Fugu data

- custom_metrics/fugu-apis.js
- package-lock.json
- package.json
Adds detection for these two new APIs.
> Fugu: Detect Ink API and VirtualKeyboard API

- custom_metrics/fugu-apis.js
- package-lock.json
- package.json
Detecting a couple more Fugu features (better).
> Add more Fugu features

- bulktest/batch_lib.inc
> Add avif as a recognized image format

- custom_metrics/fugu-apis.js
- package-lock.json
- package.json
> Add HapticsDevice API
